### ISSUE TITLE
Get started button is 404

### ISSUE THREAD

**Issue by FeynmanZhou** [litmuschaos/litmus-website-2#16]
You can reproduce this bug on the [landing page](https://litmuschaos.io/).

![image](https://user-images.githubusercontent.com/40452856/130834599-55b4b6af-9099-4a2f-a2e4-4c5e04add6ea.png)
![image](https://user-images.githubusercontent.com/40452856/130834632-5c10baa4-6f35-49bb-ba0c-7889ad734740.png)

**Comment by hrishavjha** [comment]
Looks like your browser has cached the older version of website. Try clearing the cache and reloading, this should fix the issue.
