### ISSUE TITLE
current website get started link redirecting to a wrong place

### ISSUE THREAD

**Issue by eran-levy** [litmuschaos/litmus-website-2#36]
Just created a pull request in the old website repo - https://github.com/litmuschaos/website-litmuschaos/pull/175

**Comment by SahilKr24** [comment]
@eran-levy If you can raise the issue and PR on this repository, that would be great. We have noted down the issue for now.

**Comment by SahilKr24** [comment]
The [issue](https://github.com/litmuschaos/website-litmuschaos/issues/174#issue-1104444743) in question.

**Comment by SahilKr24** [comment]
@eran-levy can you share a snip or location of the exact link/button which is redirecting to the wrong place.
I did a quick search and I'm afraid I couldn't find any links that point to: https://docs.litmuschaos.io/docs/getstarted/
Thanks.

**Comment by eran-levy** [comment]
funny it looks like the page was cached in my browser: 
![image](https://user-images.githubusercontent.com/584783/149634141-df9187b2-fa1e-4eed-85b7-662caf948f9c.png)

navigating in incognito shows the new website in this repo
