### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by kitarp29** [litmuschaos/litmus-website-2#37]
The link provided in the repo is Broken
[litmus-2-0.vercel.app](http://litmus-2-0.vercel.app/)
This seems to be taken down. Needed to be replaced by https://litmuschaos.io/
![image](https://user-images.githubusercontent.com/56778773/157533045-d5916385-a893-4e61-9b8f-be9ccf27e982.png)

**Comment by 0xSaksham** [comment]
I can do it.

Please assign me the same.

**Comment by Arya-Gupta** [comment]
I want to work on this issue. Can I please be assigned?
